// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v3.0.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1656

#include "LoggerI.h"
#include <iostream>

// Implementation skeleton constructor
Logger_i::Logger_i ()
{
	verbose(true);
}

// Implementation skeleton destructor
Logger_i::~Logger_i ()
{
}

::CORBA::Boolean Logger_i::verbose (
  void)
{
	return verboso;
}

void Logger_i::verbose (
  ::CORBA::Boolean verbose)
{
	verboso = verbose;
}

void Logger_i::log (
  ::ErrorType prioridade,
  const std::string endereco,
  ::CORBA::UShort pid,
  ::CORBA::ULong hora,
  const std::string mensagem)
{
	std::string ErrorNames[] = {"DEBUG", "WARNING", "ERROR", "CRITICAL"};
  	if (verbose() == true){
		std::cout << "Severidade: " << ErrorNames[prioridade] << std::endl;
		std::cout << "Endereço: " << endereco << std::endl;
		std::cout << "PID: " << pid << std::endl;
		std::cout << "Hora: " << hora << std::endl; 
		std::cout << "Mensagem: " << mensagem << std::endl;
		std::cout << "" << std::endl;
	}
}

